"""Digest rendering and delivery.

The digest leads with papers that touch a stored research gap, since that is the
point of the watcher; everything else relevant follows as a plain reading list.
"""
import asyncio
import json
import logging
import os
import smtplib
from datetime import date
from email.message import EmailMessage
from typing import List

import httpx

logger = logging.getLogger(__name__)

RELATIONSHIP_LABELS = {
    "fills": "FILLS",
    "partially_addresses": "partially addresses",
    "contradicts": "CONTRADICTS",
    "informs": "informs",
}
# Ordering for the digest: a filled gap is the headline, context is the footnote
RELATIONSHIP_RANK = {"fills": 0, "contradicts": 1, "partially_addresses": 2, "informs": 3}

# Only these count as a paper acting on a gap. An 'informs' link is background reading,
# so it is noted against the paper in the reading list rather than leading the digest.
HEADLINE_RELATIONSHIPS = {"fills", "contradicts", "partially_addresses"}


def _paper_line(paper: dict, indent: str = "") -> str:
    authors = paper.get("authors") or "Unknown authors"
    if len(authors) > 120:
        authors = authors[:120].rsplit(",", 1)[0] + " et al."
    return (
        f"**[{paper['title']}]({paper['url']})**  \n"
        f"{indent}{authors} — *{paper['source']}*, {paper.get('published') or 'date unknown'}"
    )


def render_digest(papers: List[dict], window_start: str, window_end: str) -> str:
    """Builds the Markdown digest from undigested, relevant papers with their gap matches."""
    def acts_on_a_gap(paper: dict) -> bool:
        return any(m["relationship"] in HEADLINE_RELATIONSHIPS for m in paper.get("matches") or [])

    flagged = [p for p in papers if acts_on_a_gap(p)]
    other = [p for p in papers if not acts_on_a_gap(p)]

    for paper in flagged:
        paper["matches"].sort(key=lambda m: (RELATIONSHIP_RANK.get(m["relationship"], 9), -m["confidence"]))
    flagged.sort(key=lambda p: (RELATIONSHIP_RANK.get(p["matches"][0]["relationship"], 9),
                                -p["matches"][0]["confidence"]))

    lines = [
        f"# Literature digest: {window_start} to {window_end}",
        "",
        f"{len(papers)} relevant new {'paper' if len(papers) == 1 else 'papers'}. "
        f"{len(flagged)} {'touches' if len(flagged) == 1 else 'touch'} a stored research gap.",
        "",
    ]

    if flagged:
        lines += ["## Papers addressing stored gaps", ""]
        for paper in flagged:
            lines.append(_paper_line(paper))
            lines.append("")
            for match in paper["matches"]:
                if match["relationship"] not in HEADLINE_RELATIONSHIPS:
                    continue
                label = RELATIONSHIP_LABELS.get(match["relationship"], match["relationship"])
                # An abstract-derived gap was never read in full, so a match against it
                # is a lead to check rather than a settled finding. Say so on the line.
                provenance = ", from abstracts" if match.get("origin") == "abstract" else ""
                lines.append(
                    f"- {label} gap **{match['title']}** "
                    f"({match['subject']}, confidence {match['confidence']:.2f}{provenance})  \n"
                    f"  {match['evidence']}"
                )
            lines.append("")
    else:
        lines += ["## Papers addressing stored gaps", "", "_None this period._", ""]

    if other:
        lines += ["## Other relevant papers", ""]
        for paper in other:
            lines.append(f"- {_paper_line(paper, indent='  ')}")
            if paper.get("relevance_reason"):
                lines.append(f"  {paper['relevance_reason']}")
            for match in paper.get("matches") or []:
                lines.append(f"  Background for gap **{match['title']}** ({match['subject']}).")
        lines.append("")

    lines += ["---", "", "_Generated by the research_gaps ambient literature watcher._"]
    return "\n".join(lines)


def _send_email_sync(subject: str, body: str) -> None:
    host = os.getenv("SMTP_HOST")
    to_addr = os.getenv("DIGEST_TO")
    if not host or not to_addr:
        raise ValueError("SMTP_HOST and DIGEST_TO must be set to send email.")

    port = int(os.getenv("SMTP_PORT", "587"))
    username = os.getenv("SMTP_USER")
    password = os.getenv("SMTP_PASSWORD")
    from_addr = os.getenv("DIGEST_FROM", username or f"watcher@{host}")

    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = from_addr
    message["To"] = to_addr
    message.set_content(body)

    if port == 465:
        server = smtplib.SMTP_SSL(host, port, timeout=30)
    else:
        server = smtplib.SMTP(host, port, timeout=30)
    with server:
        if port != 465:
            server.starttls()
        if username and password:
            server.login(username, password)
        server.send_message(message)


async def send_email(subject: str, body: str) -> None:
    await asyncio.to_thread(_send_email_sync, subject, body)
    logger.info(f"Digest emailed to {os.getenv('DIGEST_TO')}.")


async def send_push(title: str, body: str) -> None:
    """Posts the digest to an ntfy topic URL, for a phone notification off the home server."""
    url = os.getenv("NTFY_URL")
    if not url:
        raise ValueError("NTFY_URL must be set to send a push notification.")
    headers = {"Title": title, "Markdown": "yes"}
    token = os.getenv("NTFY_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(url, content=body.encode("utf-8"), headers=headers)
        response.raise_for_status()
    logger.info("Digest pushed to ntfy.")


async def deliver(digest: str, subject: str, channels: List[str]) -> None:
    """Delivers on each requested channel; a failing channel never blocks the others."""
    for channel in channels:
        try:
            if channel == "email":
                await send_email(subject, digest)
            elif channel == "push":
                await send_push(subject, digest)
            else:
                logger.warning(f"Unknown delivery channel '{channel}'; skipped.")
        except Exception as e:
            logger.error(f"Delivery via '{channel}' failed: {e}")
